# Generated by Django 4.2.4 on 2023-09-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_article_delete_login_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('footertext', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(default=20, max_length=100)),
                ('favicon', models.ImageField(upload_to='assets/img/')),
                ('pagelogo', models.ImageField(upload_to='assets/img/')),
                ('signuplogo', models.ImageField(upload_to='assets/img/')),
            ],
        ),
    ]
