# Generated by Django 4.2.4 on 2023-10-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_remove_page_setting_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Acct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intense', models.CharField(default='hmmmed', max_length=200)),
                ('name', models.CharField(default='adepoju', max_length=200)),
                ('picture', models.ImageField(default='assets/img/logo.png', upload_to='assets/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Create_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hmmmed', max_length=200)),
                ('address', models.CharField(default='ayekale', max_length=200)),
                ('email', models.EmailField(default='hammed@gmail.com', max_length=200)),
                ('username', models.CharField(default='adppoju', max_length=200)),
                ('picture', models.ImageField(default='assets/img/logo.png', upload_to='assets/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Open_Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='hmmmed', max_length=200)),
                ('model', models.CharField(default='adepoju', max_length=200)),
                ('system_role', models.CharField(default='ayekale', max_length=200)),
                ('prompt', models.CharField(default='hammedgmailcom', max_length=200)),
                ('picture', models.ImageField(default='assets/img/logo.png', upload_to='assets/img/')),
            ],
        ),
    ]
